
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s

database:
  host: "localhost"
  port: 5433
  user: "root"
  password: "r00t"
  database: "mikrobill"
  ssl_mode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 60 # minutes

jwt:
  secret_key: "a9f1c0e2c7b548c69dfbfa1fbd4ee9c1e817b4f2dc76a89fae2c33d9b27f541e"
  token_duration: 4320h
  refresh_duration: 168h

redis:
  host: "localhost"
  port: 6379

crypto:
  encryption_key: "fa786bab728dea30dbeabe3e4d7acf33"

logger:
  environment: "production" # development or production
